### ISSUE TITLE
FATAL -- : [a7326e4b-90ff-4a37-b963-b8afc3cdc142] Psych::SyntaxError ((/app/conf ig/chats.yml): did not find expected alphabetic or numeric character while scann ing an alias at line 33 column 9):

### ISSUE THREAD

**Issue by prdpspkt** [dfens/john-doe#1]

**Comment by dfens** [comment]
It seems that your `yml` file does not have valid syntax

**Comment by prdpspkt** [comment]
I have used your default yml file and it shows error. I'm new to yml and couldn't understand why there is problem. If you have time please review file and tell me the error. Thanks in advance.

**Comment by dfens** [comment]
default.yml fixed

**Comment by prdpspkt** [comment]
Thank you very much. I will try.

**Comment by prdpspkt** [comment]
This kind of error is arised again.
RegexpError (unmatched close parenthesis: /^:-)/i):

**Comment by Virus-Hunter** [comment]
I'm fairly certain the problem is that in your default.yml, many of the patterns and responses don't use quotation marks. For example
`hello:
  patterns:
    p1: hello *
    p1a: hello
    p2: hi
    p3: goodmorning *
    p3a: hello
    p4: goodday *
    p4a: goodday
  responses:
    r1: hello 
    r2: hi
    r3: goodmorning
r4: goodday`
didn't work for me, but when I added quotation marks to them all like
`hello:
  patterns:
    p1: "hello *"
    p1a: "hello"
    p2: "hi"
    p3: "goodmorning *"
    p3a: "hello"
    p4: "goodday *"
    p4a: "goodday"
  responses:
    r1: "hello" 
    r2: "hi"
    r3: "goodmorning"
    r4: "goodday"`
everything worked properly.

**Comment by dfens** [comment]
Hi,

this yaml was created by me 6 years ago while starting from "*" was legal. File updated, please ccheck
